BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MBTEST';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE MBTEST (ID INT PRIMARY KEY, NAME VARCHAR(20));
CREATE SEQUENCE mbtest_seq START WITH 1;

CREATE OR REPLACE TRIGGER test_trigger
  BEFORE INSERT ON MBTEST
  FOR EACH ROW
BEGIN
  :new.ID := mbtest_seq.nextval;
END;

INSERT INTO MBTEST (NAME) VALUES ('장은학');